#!/bin/bash
#------------------------------------------------------------------------!
# add each value of columns to compute sum of values in a file
# Written by: Rahul Verma
#------------------------------------------------------------------------!

echo "FILENAME .."
read filename

echo "`head -n5 $filename`"
echo "..."
#echo 'COLUMN INDEX'
#read indx

echo " sum column 1:  `awk '{s+=$1} END {print s}' $filename`"
echo " sum column 2:  `awk '{s+=$2} END {print s}' $filename`"
echo " sum column 3:  `awk '{s+=$3} END {print s}' $filename`"
#awk '{s+=$3} END {print s}' $filename
